production:
  server: "https://damp-temple-86099.herokuapp.com/faye"

#this is the address of this heroku app once you’ve deployed it, plus the `/faye` extension.

  secret_token: "bdd3050d9059878295a116c79acd277dbeb8e2e886920e5bc501f5e424b184be"
  signature_expiration: 3600 # one day
